"""init

Revision ID: 2d0bea544274
Revises: 
Create Date: 2026-04-23 04:34:53.486346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d0bea544274'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_outputs', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('agent_outputs', 'agent_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('agent_outputs', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('projects', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('agent_outputs', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('agent_outputs', 'agent_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('agent_outputs', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
